name: lighthouse-test

on:
  push:
  workflow_dispatch:

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies using pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build project
        run: pnpm build

      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: './lighthouserc.json'
          temporaryPublicStorage: true
          runs: 3
